/**
 * Inference adapters.
 *
 * - ZGComputeInference talks to 0G's TEE-verified inference broker.
 * - MockInference is a deterministic offline stand-in used in tests + when
 *   the broker is unavailable. Critically, generateCode produces a schema-valid
 *   stub skill so the self-evolution loop can run in CI / on a fresh laptop.
 *
 * Resilience: ZGComputeInference falls back to MockInference if the broker
 * call fails. The demo path never breaks just because compute is flaky.
 */

import type { CodeGenOpts, CodeGenResult, Inference, InferenceOpts } from '../types';

export class MockInference implements Inference {
  async generate(opts: InferenceOpts): Promise<string> {
    // Echo a deterministic answer that satisfies typical task assertions.
    const stamp = `[mock] ${(opts.prompt ?? '').slice(0, 40)}`;
    if (opts.jsonMode) return JSON.stringify({ stamp, ok: true });
    return `${stamp} — abstract: This is a mock summary.`;
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    const tag = inferTagFromTask(opts.task.description);
    const code = `
// Generated by MockInference for task ${opts.task.id}
// Tag: ${tag}
export async function run(input) {
  // Stub that returns success-criteria-shaped output
  return {
    abstract: "Mock skill output for ${tag}",
    inputs: input,
    generatedBy: "mock"
  };
}
`.trim();
    return {
      code,
      suggestedTag: tag,
      schemaIn: { type: 'object', properties: {}, additionalProperties: true },
      schemaOut: {
        type: 'object',
        properties: { abstract: { type: 'string' } },
        required: ['abstract'],
      },
      reasoning: 'mock-inference-stub',
    };
  }
}

function inferTagFromTask(description: string): string {
  const d = description.toLowerCase();
  if (d.includes('arxiv') || d.includes('paper')) return 'fetch.arxiv';
  if (d.includes('weather')) return 'fetch.weather';
  if (d.includes('price') || d.includes('quote')) return 'fetch.price';
  if (d.includes('summari')) return 'text.summarize';
  return 'general.task';
}

// ──────────────────────────────────────────────────────────────────
// 0G Compute (real, TEE-verified inference)
// ──────────────────────────────────────────────────────────────────

export interface ZGComputeOpts {
  brokerUrl: string;
  privateKey: string;
  model?: string;
  /** Falls back to MockInference if true on any broker error. Default: true. */
  fallbackToMock?: boolean;
}

/**
 * 0G Compute broker adapter.
 *
 * The full implementation uses `@0glabs/0g-serving-broker`. We keep the wiring
 * abstract so:
 *   1. Tests can run without 0G credentials
 *   2. The demo can fall back to MockInference when the broker is down
 *
 * TODO (in WAKEUP.md): bun add @0glabs/0g-serving-broker, replace the
 * `actuallyGenerate` method body with the broker SDK call. Until then,
 * ZGComputeInference behaves identically to MockInference.
 */
export class ZGComputeInference implements Inference {
  private fallback = new MockInference();

  constructor(private opts: ZGComputeOpts) {}

  async generate(opts: InferenceOpts): Promise<string> {
    try {
      return await this.actuallyGenerate(opts);
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generate(opts);
      }
      throw err;
    }
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    try {
      const json = await this.actuallyGenerate({
        prompt: this.codeGenPrompt(opts),
        jsonMode: true,
      });
      return JSON.parse(json) as CodeGenResult;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generateCode(opts);
      }
      throw err;
    }
  }

  // -------- private --------

  private async actuallyGenerate(_opts: InferenceOpts): Promise<string> {
    // TODO: wire @0glabs/0g-serving-broker here.
    // For now we throw so the fallback kicks in. This means a freshly cloned
    // repo can run the demo end-to-end against MockInference without 0G creds.
    throw new Error('zg-compute-not-wired-yet');
  }

  private codeGenPrompt(opts: CodeGenOpts): string {
    return `You are a skill generator for a Clawforger agent.

Output STRICT JSON matching this shape:
{
  "code": "<TypeScript module that exports run(input)>",
  "suggestedTag": "<dotted.capability.tag>",
  "schemaIn": { "type": "object", ... },
  "schemaOut": { "type": "object", ... },
  "reasoning": "<short explanation>"
}

The module runs in a Bun isolated worker. Allowed: fetch, JSON, basic JS. Forbidden: eval, fs, require.

Task description: ${opts.task.description}
Task inputs example: ${JSON.stringify(opts.task.inputs)}
Existing skills: ${opts.existingSkills.map((s) => s.capabilityTag).join(', ') || 'none'}

Respond with JSON only, no prose.`;
  }
}
