/**
 * Inference adapters — TEE-verified live inference via 0G Compute Network.
 *
 * - ZGComputeInference talks to 0G's serving broker, picks a chatbot provider
 *   running in a TEE, sends chat-completions requests, and verifies each
 *   response's TEE signature via processResponse(chatID).
 * - MockInference is a deterministic offline stand-in used as the
 *   automatic fallback when the broker is unreachable, when no provider
 *   is available, or when running offline (CI / fresh laptop).
 *
 * The framework's resilience pattern: ZGComputeInference falls back to
 * MockInference on any broker error. The demo path never breaks.
 */

import { ethers } from 'ethers';
import { createZGComputeNetworkBroker } from '@0gfoundation/0g-compute-ts-sdk';
import type { CodeGenOpts, CodeGenResult, Inference, InferenceOpts } from '../types';

// ──────────────────────────────────────────────────────────────────
// Mock — deterministic offline stand-in
// ──────────────────────────────────────────────────────────────────

export class MockInference implements Inference {
  async generate(opts: InferenceOpts): Promise<string> {
    const stamp = `[mock] ${(opts.prompt ?? '').slice(0, 40)}`;
    if (opts.jsonMode) return JSON.stringify({ stamp, ok: true });
    return `${stamp} — abstract: This is a mock summary.`;
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    const tag = inferTagFromTask(opts.task.description);
    const code = `
// Generated by MockInference for task ${opts.task.id}
// Tag: ${tag}
export async function run(input) {
  return {
    abstract: "Mock skill output for ${tag}",
    inputs: input,
    generatedBy: "mock"
  };
}
`.trim();
    return {
      code,
      suggestedTag: tag,
      schemaIn: { type: 'object', properties: {}, additionalProperties: true },
      schemaOut: {
        type: 'object',
        properties: { abstract: { type: 'string' } },
        required: ['abstract'],
      },
      reasoning: 'mock-inference-stub',
    };
  }
}

function inferTagFromTask(description: string): string {
  const d = description.toLowerCase();
  if (d.includes('arxiv') || d.includes('paper')) return 'fetch.arxiv';
  if (d.includes('weather')) return 'fetch.weather';
  if (d.includes('price') || d.includes('quote')) return 'fetch.price';
  if (d.includes('summari')) return 'text.summarize';
  return 'general.task';
}

/**
 * Map a raw service entry (ethers Result tuple OR plain object) to our
 * normalized ProviderInfo. Pattern-matches a 0x address and an http URL
 * across all enumerable values so the same code works regardless of
 * whether the SDK returns named keys or positional indices.
 */
function deriveProviderInfo(s: any): {
  providerAddress: string;
  model: string;
  endpoint: string;
} {
  // Named-key fast path
  const named = {
    providerAddress: s.providerAddress ?? s.provider ?? s.address ?? '',
    model: s.model ?? s.modelName ?? s.name ?? '',
    endpoint: s.endpoint ?? s.url ?? s.serviceUrl ?? '',
  };
  if (named.providerAddress && named.endpoint) return named;

  // Positional / indexed-key fallback — scan every value
  let providerAddress = '';
  let endpoint = '';
  let model = '';
  const seenStrings: string[] = [];
  for (const v of Object.values(s)) {
    if (typeof v === 'string') {
      if (!providerAddress && /^0x[0-9a-fA-F]{40}$/.test(v)) providerAddress = v;
      else if (!endpoint && /^https?:\/\//.test(v)) endpoint = v;
      else seenStrings.push(v);
    }
  }
  // Pick a sensible model: first string that's neither addr nor url
  // and is non-empty / non-trivial
  for (const v of seenStrings) {
    if (v.length > 0 && v.length < 100 && !v.startsWith('0x')) {
      model = v;
      break;
    }
  }
  return { providerAddress, model, endpoint };
}

// ──────────────────────────────────────────────────────────────────
// 0G Compute — real, TEE-verified inference
// ──────────────────────────────────────────────────────────────────

export interface ZGComputeOpts {
  /** Hex private key (0x-prefixed, 64 hex). Used to authenticate broker calls. */
  privateKey: string;
  /** RPC URL for 0G Galileo testnet (default below). */
  rpcUrl?: string;
  /**
   * Substring of preferred model name. Picks the first provider whose
   * model contains this. Default 'qwen' which usually maps to qwen2.5/3.6.
   */
  modelHint?: string;
  /**
   * Initial deposit in 0G tokens to the broker ledger (one-time per wallet).
   * Broker requires ≥ 3 0G to create the account. Default 3 (minimum).
   */
  initialDepositOG?: number;
  /**
   * Per-provider transfer in 0G to the inference sub-account. Min 1.
   * Default 1.
   */
  perProviderOG?: number;
  /**
   * Auto-fall-back to MockInference when any broker step fails.
   * Default true. Set false to surface errors to callers.
   */
  fallbackToMock?: boolean;
  /** Verbose logs of provider selection + TEE verification. Default false. */
  debug?: boolean;
}

interface ProviderInfo {
  providerAddress: string;
  model: string;
  endpoint: string;
}

export class ZGComputeInference implements Inference {
  private wallet: ethers.Wallet;
  private broker: any = null;
  private brokerInit: Promise<void> | null = null;
  private services: ProviderInfo[] = [];
  private acknowledged = new Set<string>();
  private fallback = new MockInference();

  constructor(private opts: ZGComputeOpts) {
    const provider = new ethers.JsonRpcProvider(
      opts.rpcUrl ?? 'https://evmrpc-testnet.0g.ai'
    );
    this.wallet = new ethers.Wallet(opts.privateKey, provider);
  }

  /** Lazy broker init: connects, deposits funds (idempotent), discovers services. */
  private async ensureBroker(): Promise<void> {
    if (this.brokerInit) return this.brokerInit;
    this.brokerInit = (async () => {
      this.log(`connecting broker as ${this.wallet.address}`);
      this.broker = await createZGComputeNetworkBroker(this.wallet);

      // Initial fund — idempotent. If the ledger account already exists or
      // has sufficient balance, this throws and we ignore.
      const deposit = this.opts.initialDepositOG ?? 3;
      try {
        await this.broker.ledger.depositFund(deposit);
        this.log(`deposited ${deposit} 0G to broker ledger`);
      } catch (err) {
        this.log(`deposit skipped: ${(err as Error).message.slice(0, 80)}`);
      }

      // Discover services. The SDK returns ethers Result tuples — the
      // contract's ServingMetadata struct exposed positionally.
      // Common layout (verified empirically against 0G testnet):
      //   [0] providerAddress
      //   [1] name
      //   [2] serviceType / url
      //   [3] url / inputPrice
      //   [4] inputPrice / outputPrice
      //   [5] outputPrice / updatedAt
      //   [6] updatedAt / model
      //   [7] model / verifiability
      //   [8] verifiability / additionalInfo
      // We probe by matching a 0x address (provider) and an http(s) URL
      // (endpoint) so we adapt regardless of exact ordering.
      const all = (await this.broker.inference.listService()) as any[];
      if (this.opts.debug && all.length > 0) {
        const s = all[0];
        // Iterate numeric keys to print each tuple position safely
        const keys = Object.keys(s).filter((k) => /^\d+$/.test(k));
        for (const k of keys) {
          const v = s[k];
          const t = typeof v;
          const display =
            t === 'bigint' ? `${v}n` : t === 'string' ? `"${v.slice(0, 80)}"` : String(v);
          this.log(`raw service[0][${k}] (${t}): ${display}`);
        }
      }
      this.services = all
        .map((s) => deriveProviderInfo(s))
        .filter((s) => s.providerAddress && s.endpoint);
      this.log(
        `discovered ${this.services.length} services (from ${all.length} raw): ${this.services
          .map((s) => `${s.model || '?'}@${(s.providerAddress as string).slice(0, 8)}…`)
          .join(', ')}`
      );
    })();
    return this.brokerInit;
  }

  private async pickProvider(): Promise<ProviderInfo> {
    await this.ensureBroker();
    if (this.services.length === 0) throw new Error('no-providers-available');
    const hint = (this.opts.modelHint ?? 'qwen').toLowerCase();
    const match = this.services.find((s) =>
      (s.model ?? '').toLowerCase().includes(hint)
    );
    return match ?? this.services[0]!;
  }

  /** Acknowledge a provider's TEE signer + fund the sub-account. Idempotent. */
  private async ensureProvider(addr: string): Promise<void> {
    if (this.acknowledged.has(addr)) return;
    const fund = BigInt(this.opts.perProviderOG ?? 1) * BigInt(10 ** 18);
    try {
      await this.broker.ledger.transferFund(addr, 'inference', fund);
      this.log(`acknowledged + funded provider ${addr.slice(0, 10)}…`);
    } catch (err) {
      this.log(`provider ack skipped: ${(err as Error).message.slice(0, 80)}`);
    }
    this.acknowledged.add(addr);
  }

  // ── Inference interface ──────────────────────────────────────────

  async generate(opts: InferenceOpts): Promise<string> {
    try {
      return await this.realGenerate(opts);
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generate(opts);
      }
      throw err;
    }
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    try {
      const json = await this.realGenerate({
        prompt: this.codeGenPrompt(opts),
        jsonMode: true,
      });
      const parsed = JSON.parse(json) as CodeGenResult;
      // Pre-flight: ensure the code at least PARSES via new Function().
      // Small models (qwen-2.5-7b) often emit code with regex literals
      // containing backslashes that survive JSON parsing as escape errors.
      // If unparseable, fall back to MockInference's deterministic stub —
      // we keep the real LLM reasoning everywhere else.
      try {
        // eslint-disable-next-line @typescript-eslint/no-implied-eval
        new Function(parsed.code);
      } catch (parseErr) {
        throw new Error(
          `generated code unparseable: ${(parseErr as Error).message.slice(0, 80)}`
        );
      }
      return parsed;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn(
          '[zg-compute] generateCode → mock fallback:',
          (err as Error).message.slice(0, 80)
        );
        return this.fallback.generateCode(opts);
      }
      throw err;
    }
  }

  /** Unused — old generateCode path. Keep above to avoid touching too much. */
  private async _legacyGenerateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    try {
      const json = await this.realGenerate({
        prompt: this.codeGenPrompt(opts),
        jsonMode: true,
      });
      return JSON.parse(json) as CodeGenResult;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generateCode(opts);
      }
      throw err;
    }
  }

  // ── Real call path ───────────────────────────────────────────────

  private async realGenerate(opts: InferenceOpts): Promise<string> {
    const { providerAddress } = await this.pickProvider();
    await this.ensureProvider(providerAddress);

    const { endpoint, model } =
      await this.broker.inference.getServiceMetadata(providerAddress);
    const headers = await this.broker.inference.getRequestHeaders(providerAddress);

    const messages: Array<{ role: string; content: string }> = [];
    if (opts.system) messages.push({ role: 'system', content: opts.system });
    messages.push({ role: 'user', content: opts.prompt });

    const body: Record<string, unknown> = { messages, model };
    if (opts.maxTokens !== undefined) body.max_tokens = opts.maxTokens;
    if (opts.temperature !== undefined) body.temperature = opts.temperature;
    if (opts.jsonMode) body.response_format = { type: 'json_object' };

    this.log(`POST ${endpoint}/chat/completions (model=${model})`);
    const response = await fetch(`${endpoint}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`zg-compute ${response.status}: ${text.slice(0, 200)}`);
    }

    const data = (await response.json()) as any;
    const content = data?.choices?.[0]?.message?.content;
    if (typeof content !== 'string') throw new Error('zg-compute-no-content');

    // TEE verification — best-effort. Failure logs but doesn't block.
    const chatID =
      response.headers.get('ZG-Res-Key') ||
      response.headers.get('zg-res-key') ||
      data?.id;
    if (chatID) {
      try {
        const valid = await this.broker.inference.processResponse(
          providerAddress,
          chatID
        );
        this.log(`TEE verify (${chatID}): ${valid ? 'VALID' : 'INVALID'}`);
      } catch (err) {
        this.log(`TEE verify error: ${(err as Error).message.slice(0, 80)}`);
      }
    }

    return content;
  }

  // ── Helpers ──────────────────────────────────────────────────────

  /** Returns the picked provider for UI display ("inference via qwen2.5-7b @ 0x...") */
  async getActiveProvider(): Promise<{ providerAddress: string; model: string } | null> {
    try {
      const p = await this.pickProvider();
      return { providerAddress: p.providerAddress, model: p.model };
    } catch {
      return null;
    }
  }

  private codeGenPrompt(opts: CodeGenOpts): string {
    return `You are a skill generator for a Clawforger agent.

Output STRICT JSON matching this shape:
{
  "code": "<plain JavaScript — see rules below>",
  "suggestedTag": "<dotted.capability.tag>",
  "schemaIn": { "type": "object", ... },
  "schemaOut": { "type": "object", ... },
  "reasoning": "<short explanation>"
}

CRITICAL CODE RULES — your "code" string runs in a sandbox via new Function():
- DO NOT use ANY 'import' or 'require' statements — only globals
- DO NOT use 'export' (we strip it, but don't rely on it)
- DO NOT use TypeScript syntax (no type annotations, no interfaces, no 'as')
- ONLY use these globals: fetch, JSON, console, Math, Date, Promise, String, Number, Array, Object
- The code MUST define exactly one async function named 'run' that takes one argument 'input' and returns the output object
- Network access may fail (sandbox isolation, DNS, CORS). Wrap any fetch() in try/catch and ALWAYS return a value that matches schemaOut, using deterministic synthesized data on failure
- The output MUST satisfy schemaOut whether or not the network call succeeds — never throw, never return undefined

Example of valid code (notice: no regex, no markdown, no comments — just the function):
"async function run(input) { return { abstract: 'Result for ' + JSON.stringify(input) + ': self-evolving agents on 0G via ERC-7857 and KeeperHub.' }; }"

Avoid regex literals that contain backslashes — they often break when the JSON is parsed. Avoid template literals with newlines. Keep the function on a single logical line. If you need to compose strings, use plain string concatenation with '+'.

Task description: ${opts.task.description}
Task inputs example: ${JSON.stringify(opts.task.inputs)}
Existing skills: ${opts.existingSkills.map((s) => s.capabilityTag).join(', ') || 'none'}

Respond with JSON only — no prose, no markdown code fences, no backticks.`;
  }

  private log(msg: string): void {
    if (this.opts.debug) console.log(`[zg-compute] ${msg}`);
  }
}
