/**
 * Inference adapters — TEE-verified live inference via 0G Compute Network.
 *
 * - ZGComputeInference talks to 0G's serving broker, picks a chatbot provider
 *   running in a TEE, sends chat-completions requests, and verifies each
 *   response's TEE signature via processResponse(chatID).
 * - MockInference is a deterministic offline stand-in used as the
 *   automatic fallback when the broker is unreachable, when no provider
 *   is available, or when running offline (CI / fresh laptop).
 *
 * The framework's resilience pattern: ZGComputeInference falls back to
 * MockInference on any broker error. The demo path never breaks.
 */

import { ethers } from 'ethers';
import { createZGComputeNetworkBroker } from '@0gfoundation/0g-compute-ts-sdk';
import type {
  ChatMessage,
  ChatResult,
  CodeGenOpts,
  CodeGenResult,
  Inference,
  InferenceOpts,
  ToolDef,
  ToolCallRequest,
} from '../types';

// ──────────────────────────────────────────────────────────────────
// Mock — deterministic offline stand-in
// ──────────────────────────────────────────────────────────────────

export class MockInference implements Inference {
  async generate(opts: InferenceOpts): Promise<string> {
    const stamp = `[mock] ${(opts.prompt ?? '').slice(0, 40)}`;
    if (opts.jsonMode) return JSON.stringify({ stamp, ok: true });
    return `${stamp} — abstract: This is a mock summary.`;
  }

  async chat(messages: ChatMessage[]): Promise<ChatResult> {
    const last = messages[messages.length - 1];
    return {
      content: `[mock reply] echo of: ${last?.content?.slice(0, 60) ?? ''}`,
      chatID: null,
      verified: false,
      providerAddress: '0x0',
      model: 'mock',
      endpoint: 'mock://local',
    };
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    const tag = inferTagFromTask(opts.task.description);
    const code = `
// Generated by MockInference for task ${opts.task.id}
// Tag: ${tag}
export async function run(input) {
  return {
    abstract: "Mock skill output for ${tag}",
    inputs: input,
    generatedBy: "mock"
  };
}
`.trim();
    // Derive a schemaIn from the task's exampleInput so the forged skill
    // has a real schema (not an empty `additionalProperties: true` blob).
    // This makes downstream tool-call inference reliable when the agent
    // has multiple forged skills exposed.
    const inputs = (opts.task.inputs ?? {}) as Record<string, unknown>;
    const properties: Record<string, { type: string }> = {};
    for (const [k, v] of Object.entries(inputs)) {
      const t = Array.isArray(v) ? 'array' : typeof v;
      properties[k] = { type: t === 'undefined' ? 'string' : t };
    }
    const schemaIn: Record<string, unknown> =
      Object.keys(properties).length > 0
        ? {
            type: 'object',
            properties,
            required: Object.keys(properties),
            additionalProperties: true,
          }
        : { type: 'object', properties: {}, additionalProperties: true };

    return {
      code,
      suggestedTag: tag,
      schemaIn,
      schemaOut: {
        type: 'object',
        properties: { abstract: { type: 'string' } },
        required: ['abstract'],
      },
      reasoning: 'mock-inference-stub',
    };
  }
}

function inferTagFromTask(description: string): string {
  const d = description.toLowerCase();
  if (d.includes('arxiv') || d.includes('paper')) return 'fetch.arxiv';
  if (d.includes('weather')) return 'fetch.weather';
  if (d.includes('price') || d.includes('quote')) return 'fetch.price';
  if (d.includes('summari')) return 'text.summarize';
  return 'general.task';
}

/**
 * Map a raw service entry (ethers Result tuple OR plain object) to our
 * normalized ProviderInfo. Pattern-matches a 0x address and an http URL
 * across all enumerable values so the same code works regardless of
 * whether the SDK returns named keys or positional indices.
 */
function deriveProviderInfo(s: any): {
  providerAddress: string;
  model: string;
  endpoint: string;
} {
  // Named-key fast path
  const named = {
    providerAddress: s.providerAddress ?? s.provider ?? s.address ?? '',
    model: s.model ?? s.modelName ?? s.name ?? '',
    endpoint: s.endpoint ?? s.url ?? s.serviceUrl ?? '',
  };
  if (named.providerAddress && named.endpoint) return named;

  // Positional / indexed-key fallback — scan every value
  let providerAddress = '';
  let endpoint = '';
  let model = '';
  const seenStrings: string[] = [];
  for (const v of Object.values(s)) {
    if (typeof v === 'string') {
      if (!providerAddress && /^0x[0-9a-fA-F]{40}$/.test(v)) providerAddress = v;
      else if (!endpoint && /^https?:\/\//.test(v)) endpoint = v;
      else seenStrings.push(v);
    }
  }
  // Pick a sensible model: first string that's neither addr nor url
  // and is non-empty / non-trivial
  for (const v of seenStrings) {
    if (v.length > 0 && v.length < 100 && !v.startsWith('0x')) {
      model = v;
      break;
    }
  }
  return { providerAddress, model, endpoint };
}

// ──────────────────────────────────────────────────────────────────
// 0G Compute — real, TEE-verified inference
// ──────────────────────────────────────────────────────────────────

export interface ZGComputeOpts {
  /** Hex private key (0x-prefixed, 64 hex). Used to authenticate broker calls. */
  privateKey: string;
  /** RPC URL for 0G Galileo testnet (default below). */
  rpcUrl?: string;
  /**
   * Substring of preferred model name. Picks the first provider whose
   * model contains this. Default 'qwen' which usually maps to qwen2.5/3.6.
   */
  modelHint?: string;
  /**
   * Top-up amount in 0G to the broker ledger when balance is below
   * `minBalanceOG`. Broker requires ≥ 3 0G to *create* the account,
   * so 3 is the safe default for a fresh wallet. Default 3.
   */
  initialDepositOG?: number;
  /**
   * Skip top-ups while the broker ledger's available balance ≥ this
   * threshold. Default 0.5 0G — enough for thousands of cheap chat
   * completions on qwen-2.5-7b. Set to 0 to force a deposit on every
   * run (legacy behavior).
   */
  minBalanceOG?: number;
  /**
   * Per-provider transfer in 0G to the inference sub-account. Min 1.
   * Default 1.
   */
  perProviderOG?: number;
  /**
   * Auto-fall-back to MockInference when any broker step fails.
   * Default true. Set false to surface errors to callers.
   */
  fallbackToMock?: boolean;
  /** Verbose logs of provider selection + TEE verification. Default false. */
  debug?: boolean;
}

interface ProviderInfo {
  providerAddress: string;
  model: string;
  endpoint: string;
}

/**
 * Pull the available (unlocked) balance out of the broker's ledger
 * struct. The SDK returns an ethers Result tuple — fields may be
 * named or positional depending on the ABI artifact. Returns 0G as a
 * float (small loss-of-precision is fine for threshold checks).
 */
function readAvailable(ledger: unknown): number {
  if (!ledger) return 0;
  const NEURON = 1e18;
  const asBig = (v: unknown): bigint | null => {
    if (typeof v === 'bigint') return v;
    if (typeof v === 'string' && /^\d+$/.test(v)) return BigInt(v);
    return null;
  };
  // Try named-field access first (works on Result tuples with ABI names)
  const obj = ledger as Record<string, unknown>;
  const total =
    asBig(obj.totalBalance) ?? asBig(obj.balance) ?? asBig(obj.amount);
  const locked = asBig(obj.locked) ?? asBig(obj.lockedBalance) ?? 0n;
  if (total !== null) {
    const free = total - locked;
    return Number(free) / NEURON;
  }
  // Positional fallback for tuple-shaped Results: collect bigints
  if (Array.isArray(ledger)) {
    const bigs = (ledger as unknown[])
      .map(asBig)
      .filter((v): v is bigint => v !== null && v > 100n);
    if (bigs.length >= 2) {
      // Convention observed on 0G testnet: [available, totalDeposited, …]
      // First bigint is available; if the order ever flips, both being
      // non-zero still yields a sensible threshold check.
      const min = bigs.reduce((a, b) => (a < b ? a : b));
      return Number(min) / NEURON;
    }
    if (bigs.length === 1) return Number(bigs[0]) / NEURON;
  }
  return 0;
}

export class ZGComputeInference implements Inference {
  private wallet: ethers.Wallet;
  private broker: any = null;
  private brokerInit: Promise<void> | null = null;
  private services: ProviderInfo[] = [];
  private acknowledged = new Set<string>();
  private fallback = new MockInference();

  constructor(private opts: ZGComputeOpts) {
    const provider = new ethers.JsonRpcProvider(
      opts.rpcUrl ?? 'https://evmrpc-testnet.0g.ai'
    );
    this.wallet = new ethers.Wallet(opts.privateKey, provider);
  }

  /**
   * Read the broker ledger for this wallet. Returns balances in 0G as
   * floats. Use to surface "compute pool" info in a UI without exposing
   * the private key. Triggers broker init if not already connected.
   */
  async getLedgerInfo(): Promise<{
    walletAddress: string;
    totalOG: number;
    lockedOG: number;
    availableOG: number;
    minDepositOG: number;
    minBalanceOG: number;
  }> {
    await this.ensureBroker();
    const ledger = await this.broker.ledger.getLedger().catch(() => null);
    const NEURON = 1e18;
    const asBig = (v: unknown): bigint | null => {
      if (typeof v === 'bigint') return v;
      if (typeof v === 'string' && /^\d+$/.test(v)) return BigInt(v);
      return null;
    };
    let totalOG = 0;
    let lockedOG = 0;
    if (ledger) {
      const obj = ledger as Record<string, unknown>;
      const total =
        asBig(obj.totalBalance) ?? asBig(obj.balance) ?? asBig(obj.amount);
      const locked =
        asBig(obj.locked) ?? asBig(obj.lockedBalance) ?? null;
      if (total !== null && locked !== null) {
        totalOG = Number(total) / NEURON;
        lockedOG = Number(locked) / NEURON;
      } else if (Array.isArray(ledger)) {
        const bigs = (ledger as unknown[])
          .map(asBig)
          .filter((v): v is bigint => v !== null && v > 100n);
        if (bigs.length >= 2) {
          // Convention: smaller value = locked/in-flight, larger = total
          const sorted = [...bigs].sort((a, b) => (a < b ? -1 : 1));
          lockedOG = Number(sorted[0]) / NEURON;
          totalOG = Number(sorted[sorted.length - 1]!) / NEURON;
        } else if (bigs.length === 1) {
          totalOG = Number(bigs[0]) / NEURON;
        }
      }
    }
    return {
      walletAddress: this.wallet.address,
      totalOG,
      lockedOG,
      availableOG: Math.max(0, totalOG - lockedOG),
      minDepositOG: this.opts.initialDepositOG ?? 3,
      minBalanceOG: this.opts.minBalanceOG ?? 0.5,
    };
  }

  /** Lazy broker init: connects, deposits funds (idempotent), discovers services. */
  private async ensureBroker(): Promise<void> {
    if (this.brokerInit) return this.brokerInit;
    this.brokerInit = (async () => {
      this.log(`connecting broker as ${this.wallet.address}`);
      this.broker = await createZGComputeNetworkBroker(this.wallet);

      // Initial fund — truly idempotent. Read the ledger first; only
      // top up if the available balance falls below `minBalanceOG`.
      // Broker requires ≥ 3 0G to *create* the account, but once it
      // exists we don't need to keep stacking — every run was adding 3
      // more 0G even though plenty was unused.
      const targetTop = this.opts.initialDepositOG ?? 3;
      const minBalance = this.opts.minBalanceOG ?? 0.5;
      try {
        const ledger = await this.broker.ledger.getLedger().catch(() => null);
        const available = ledger ? readAvailable(ledger) : 0;
        if (available >= minBalance) {
          this.log(
            `broker ledger ok: ${available.toFixed(3)} 0G available (≥ ${minBalance} 0G threshold) — skipping deposit`
          );
        } else {
          await this.broker.ledger.depositFund(targetTop);
          this.log(
            `topped up ${targetTop} 0G (had ${available.toFixed(3)} 0G, below ${minBalance} 0G threshold)`
          );
        }
      } catch (err) {
        // Account didn't exist yet, or read failed — fall back to a one-time
        // create-funded deposit. Still safer than the old unconditional add.
        try {
          await this.broker.ledger.depositFund(targetTop);
          this.log(`first-time deposit ${targetTop} 0G to broker ledger`);
        } catch (err2) {
          this.log(`deposit skipped: ${(err2 as Error).message.slice(0, 80)}`);
        }
      }

      // Discover services. The SDK returns ethers Result tuples — the
      // contract's ServingMetadata struct exposed positionally.
      // Common layout (verified empirically against 0G testnet):
      //   [0] providerAddress
      //   [1] name
      //   [2] serviceType / url
      //   [3] url / inputPrice
      //   [4] inputPrice / outputPrice
      //   [5] outputPrice / updatedAt
      //   [6] updatedAt / model
      //   [7] model / verifiability
      //   [8] verifiability / additionalInfo
      // We probe by matching a 0x address (provider) and an http(s) URL
      // (endpoint) so we adapt regardless of exact ordering.
      const all = (await this.broker.inference.listService()) as any[];
      if (this.opts.debug && all.length > 0) {
        const s = all[0];
        // Iterate numeric keys to print each tuple position safely
        const keys = Object.keys(s).filter((k) => /^\d+$/.test(k));
        for (const k of keys) {
          const v = s[k];
          const t = typeof v;
          const display =
            t === 'bigint' ? `${v}n` : t === 'string' ? `"${v.slice(0, 80)}"` : String(v);
          this.log(`raw service[0][${k}] (${t}): ${display}`);
        }
      }
      this.services = all
        .map((s) => deriveProviderInfo(s))
        .filter((s) => s.providerAddress && s.endpoint);
      this.log(
        `discovered ${this.services.length} services (from ${all.length} raw): ${this.services
          .map((s) => `${s.model || '?'}@${(s.providerAddress as string).slice(0, 8)}…`)
          .join(', ')}`
      );
    })();
    return this.brokerInit;
  }

  private async pickProvider(): Promise<ProviderInfo> {
    await this.ensureBroker();
    if (this.services.length === 0) throw new Error('no-providers-available');
    const hint = (this.opts.modelHint ?? 'qwen').toLowerCase();
    const match = this.services.find((s) =>
      (s.model ?? '').toLowerCase().includes(hint)
    );
    return match ?? this.services[0]!;
  }

  /** Acknowledge a provider's TEE signer + fund the sub-account. Idempotent. */
  private async ensureProvider(addr: string): Promise<void> {
    if (this.acknowledged.has(addr)) return;
    const fund = BigInt(this.opts.perProviderOG ?? 1) * BigInt(10 ** 18);
    try {
      await this.broker.ledger.transferFund(addr, 'inference', fund);
      this.log(`acknowledged + funded provider ${addr.slice(0, 10)}…`);
    } catch (err) {
      this.log(`provider ack skipped: ${(err as Error).message.slice(0, 80)}`);
    }
    this.acknowledged.add(addr);
  }

  // ── Inference interface ──────────────────────────────────────────

  async generate(opts: InferenceOpts): Promise<string> {
    try {
      return await this.realGenerate(opts);
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generate(opts);
      }
      throw err;
    }
  }

  async generateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    try {
      const json = await this.realGenerate({
        prompt: this.codeGenPrompt(opts),
        jsonMode: true,
      });
      const parsed = JSON.parse(json) as CodeGenResult;
      // Pre-flight: ensure the code at least PARSES via new Function().
      // Small models (qwen-2.5-7b) often emit code with regex literals
      // containing backslashes that survive JSON parsing as escape errors.
      // If unparseable, fall back to MockInference's deterministic stub —
      // we keep the real LLM reasoning everywhere else.
      try {
        // eslint-disable-next-line @typescript-eslint/no-implied-eval
        new Function(parsed.code);
      } catch (parseErr) {
        throw new Error(
          `generated code unparseable: ${(parseErr as Error).message.slice(0, 80)}`
        );
      }
      return parsed;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn(
          '[zg-compute] generateCode → mock fallback:',
          (err as Error).message.slice(0, 80)
        );
        return this.fallback.generateCode(opts);
      }
      throw err;
    }
  }

  /**
   * Multi-message chat with full TEE-verification metadata.
   *
   * Used by the Studio's /agents/:id/chat route — returns the chatID and
   * verified flag so the UI can show a "TEE verified ✓" seal next to each
   * assistant turn. Falls back to a mock reply if the broker is down.
   */
  async chat(
    messages: ChatMessage[],
    opts?: { tools?: ToolDef[]; toolChoice?: 'auto' | 'required' | 'none' }
  ): Promise<ChatResult> {
    try {
      const provider = await this.pickProvider();
      await this.ensureProvider(provider.providerAddress);

      const { endpoint, model } = await this.broker.inference.getServiceMetadata(
        provider.providerAddress
      );
      const headers = await this.broker.inference.getRequestHeaders(
        provider.providerAddress
      );

      const body: Record<string, unknown> = { messages, model };
      if (opts?.tools && opts.tools.length > 0) {
        body.tools = opts.tools;
        body.tool_choice = opts.toolChoice ?? 'auto';
      }

      this.log(
        `POST ${endpoint}/chat/completions (chat, ${messages.length} msgs, ${
          opts?.tools?.length ?? 0
        } tools, model=${model})`
      );
      const response = await fetch(`${endpoint}/chat/completions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...headers },
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const text = await response.text();
        throw new Error(`zg-compute ${response.status}: ${text.slice(0, 200)}`);
      }
      const data = (await response.json()) as any;
      const choiceMsg = data?.choices?.[0]?.message;
      const content = choiceMsg?.content ?? '';
      const toolCalls = choiceMsg?.tool_calls as ToolCallRequest[] | undefined;
      if (typeof content !== 'string' && !toolCalls) {
        throw new Error('zg-compute-no-content');
      }

      const chatID =
        response.headers.get('ZG-Res-Key') ||
        response.headers.get('zg-res-key') ||
        data?.id ||
        null;

      let verified = false;
      if (chatID) {
        try {
          verified = !!(await this.broker.inference.processResponse(
            provider.providerAddress,
            chatID
          ));
          this.log(`TEE verify (${chatID}): ${verified ? 'VALID' : 'INVALID'}`);
        } catch (err) {
          this.log(`TEE verify error: ${(err as Error).message.slice(0, 80)}`);
        }
      }

      // Qwen-2.5 emits its NATIVE tool-call format in `content` instead of
      // the OpenAI `tool_calls` field when the proxy doesn't translate.
      // Detect markers like ✿FUNCTION✿/✿ARGS✿ or <tool_call>{...}</tool_call>
      // and synthesize OpenAI-shaped calls so the rest of the loop works.
      let parsedToolCalls: ToolCallRequest[] | undefined = toolCalls;
      let cleanContent = typeof content === 'string' ? content : '';
      if ((!parsedToolCalls || parsedToolCalls.length === 0) && cleanContent) {
        const synth = parseQwenNativeToolCalls(cleanContent, opts?.tools);
        if (synth.calls.length > 0) {
          parsedToolCalls = synth.calls;
          cleanContent = synth.cleaned;
          this.log(`parsed ${synth.calls.length} qwen-native tool call(s) from content`);
        }
      }

      const result: ChatResult = {
        content: cleanContent,
        chatID,
        verified,
        providerAddress: provider.providerAddress,
        model,
        endpoint,
      };
      if (parsedToolCalls && parsedToolCalls.length > 0) result.toolCalls = parsedToolCalls;
      return result;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] chat → mock fallback:', (err as Error).message);
        return this.fallback.chat!(messages);
      }
      throw err;
    }
  }

  /** Unused — old generateCode path. Keep above to avoid touching too much. */
  private async _legacyGenerateCode(opts: CodeGenOpts): Promise<CodeGenResult> {
    try {
      const json = await this.realGenerate({
        prompt: this.codeGenPrompt(opts),
        jsonMode: true,
      });
      return JSON.parse(json) as CodeGenResult;
    } catch (err) {
      if (this.opts.fallbackToMock !== false) {
        console.warn('[zg-compute] falling back to mock:', (err as Error).message);
        return this.fallback.generateCode(opts);
      }
      throw err;
    }
  }

  // ── Real call path ───────────────────────────────────────────────

  private async realGenerate(opts: InferenceOpts): Promise<string> {
    const { providerAddress } = await this.pickProvider();
    await this.ensureProvider(providerAddress);

    const { endpoint, model } =
      await this.broker.inference.getServiceMetadata(providerAddress);
    const headers = await this.broker.inference.getRequestHeaders(providerAddress);

    const messages: Array<{ role: string; content: string }> = [];
    if (opts.system) messages.push({ role: 'system', content: opts.system });
    messages.push({ role: 'user', content: opts.prompt });

    const body: Record<string, unknown> = { messages, model };
    if (opts.maxTokens !== undefined) body.max_tokens = opts.maxTokens;
    if (opts.temperature !== undefined) body.temperature = opts.temperature;
    if (opts.jsonMode) body.response_format = { type: 'json_object' };

    this.log(`POST ${endpoint}/chat/completions (model=${model})`);
    const response = await fetch(`${endpoint}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`zg-compute ${response.status}: ${text.slice(0, 200)}`);
    }

    const data = (await response.json()) as any;
    const content = data?.choices?.[0]?.message?.content;
    if (typeof content !== 'string') throw new Error('zg-compute-no-content');

    // TEE verification — best-effort. Failure logs but doesn't block.
    const chatID =
      response.headers.get('ZG-Res-Key') ||
      response.headers.get('zg-res-key') ||
      data?.id;
    if (chatID) {
      try {
        const valid = await this.broker.inference.processResponse(
          providerAddress,
          chatID
        );
        this.log(`TEE verify (${chatID}): ${valid ? 'VALID' : 'INVALID'}`);
      } catch (err) {
        this.log(`TEE verify error: ${(err as Error).message.slice(0, 80)}`);
      }
    }

    return content;
  }

  // ── Helpers ──────────────────────────────────────────────────────

  /** Returns the picked provider for UI display ("inference via qwen2.5-7b @ 0x...") */
  async getActiveProvider(): Promise<{ providerAddress: string; model: string } | null> {
    try {
      const p = await this.pickProvider();
      return { providerAddress: p.providerAddress, model: p.model };
    } catch {
      return null;
    }
  }

  private codeGenPrompt(opts: CodeGenOpts): string {
    return `You are a skill generator for a Clawforger agent.

Output STRICT JSON matching this shape:
{
  "code": "<plain JavaScript — see rules below>",
  "suggestedTag": "<dotted.capability.tag>",
  "schemaIn": { "type": "object", ... },
  "schemaOut": { "type": "object", ... },
  "reasoning": "<short explanation>"
}

CRITICAL CODE RULES — your "code" string runs in a sandbox via new Function():
- DO NOT use ANY 'import' or 'require' statements — only globals
- DO NOT use 'export' (we strip it, but don't rely on it)
- DO NOT use TypeScript syntax (no type annotations, no interfaces, no 'as')
- ONLY use these globals: fetch, JSON, console, Math, Date, Promise, String, Number, Array, Object
- The code MUST define exactly one async function named 'run' that takes one argument 'input' and returns the output object
- Network access may fail (sandbox isolation, DNS, CORS). Wrap any fetch() in try/catch and ALWAYS return a value that matches schemaOut, using deterministic synthesized data on failure
- The output MUST satisfy schemaOut whether or not the network call succeeds — never throw, never return undefined

Example of valid code (notice: no regex, no markdown, no comments — just the function):
"async function run(input) { return { abstract: 'Result for ' + JSON.stringify(input) + ': self-evolving agents on 0G via ERC-7857 and KeeperHub.' }; }"

Avoid regex literals that contain backslashes — they often break when the JSON is parsed. Avoid template literals with newlines. Keep the function on a single logical line. If you need to compose strings, use plain string concatenation with '+'.

Task description: ${opts.task.description}
Task inputs example: ${JSON.stringify(opts.task.inputs)}
Existing skills: ${opts.existingSkills.map((s) => s.capabilityTag).join(', ') || 'none'}

Respond with JSON only — no prose, no markdown code fences, no backticks.`;
  }

  private log(msg: string): void {
    if (this.opts.debug) console.log(`[zg-compute] ${msg}`);
  }
}

// ──────────────────────────────────────────────────────────────────
// Qwen-native tool-call parser
//
// qwen-2.5-7b on 0G's proxy sometimes emits its training-time format
// (✿FUNCTION✿:/✿ARGS✿: or <tool_call>{...}</tool_call>) directly in the
// content field instead of the OpenAI tool_calls schema. This parser
// detects those markers and synthesizes OpenAI-shaped tool calls so
// the upstream loop can run them like any other tool call.
// ──────────────────────────────────────────────────────────────────

interface NativeParseResult {
  calls: ToolCallRequest[];
  cleaned: string; // content with the tool-call tokens stripped
}

function parseQwenNativeToolCalls(
  content: string,
  knownTools?: ToolDef[]
): NativeParseResult {
  const calls: ToolCallRequest[] = [];
  let counter = 0;
  const newCallId = () => `qwen-${Date.now()}-${counter++}`;

  // Spans we successfully consumed — used to rebuild cleaned text.
  const spans: Array<[number, number]> = [];

  // Pattern 1: <tool_call>{...}</tool_call>
  {
    const rx = /<tool_call>([\s\S]*?)<\/tool_call>/gi;
    let m: RegExpExecArray | null;
    while ((m = rx.exec(content))) {
      try {
        const obj = JSON.parse((m[1] ?? '').trim());
        const name = typeof obj.name === 'string' ? obj.name : null;
        if (name) {
          calls.push({
            id: newCallId(),
            type: 'function',
            function: {
              name,
              arguments: JSON.stringify(obj.arguments ?? obj.parameters ?? {}),
            },
          });
        }
      } catch {
        /* skip */
      }
      spans.push([m.index, m.index + m[0].length]);
    }
  }

  // Pattern 2: ✿FUNCTION✿: name [\n] ✿ARGS✿: { ... balanced ... }
  // We hand-walk braces to handle nested JSON objects.
  const findFn = /✿FUNCTION✿\s*:\s*([\w.\-]+)/g;
  let fnMatch: RegExpExecArray | null;
  while ((fnMatch = findFn.exec(content))) {
    const name = fnMatch[1] ?? '';
    if (!name) continue;
    const fnStart = fnMatch.index;
    const argsKey = '✿ARGS✿';
    const argsKeyAt = content.indexOf(argsKey, fnStart + fnMatch[0].length);
    if (argsKeyAt === -1) continue;
    const after = content.indexOf(':', argsKeyAt);
    if (after === -1) continue;
    const braceStart = content.indexOf('{', after);
    if (braceStart === -1) continue;
    const braceEnd = findMatchingBrace(content, braceStart);
    if (braceEnd === -1) continue;
    const argsRaw = content.slice(braceStart, braceEnd + 1);
    try {
      const args = JSON.parse(argsRaw);
      calls.push({
        id: newCallId(),
        type: 'function',
        function: { name, arguments: JSON.stringify(args) },
      });
      spans.push([fnStart, braceEnd + 1]);
    } catch {
      /* skip malformed */
    }
  }

  // Pattern 3: bare ✿ARGS✿: { ... } with no preceding FUNCTION marker.
  // Skip ones already covered by Pattern 2 (overlap with spans). Try to
  // pick up an explicit name from a leading `_skill_<name>` / `function:<name>`
  // pseudo-marker that some qwen variants emit just before ✿ARGS✿.
  const findArgs = /✿ARGS✿\s*:/g;
  let argsMatch: RegExpExecArray | null;
  while ((argsMatch = findArgs.exec(content))) {
    const at = argsMatch.index;
    if (spans.some(([s, e]) => at >= s && at < e)) continue;
    const braceStart = content.indexOf('{', at);
    if (braceStart === -1) continue;
    const braceEnd = findMatchingBrace(content, braceStart);
    if (braceEnd === -1) continue;
    const argsRaw = content.slice(braceStart, braceEnd + 1);
    try {
      const args = JSON.parse(argsRaw);

      // Look back up to 200 chars for a name marker
      const lookback = content.slice(Math.max(0, at - 200), at);
      let explicitName: string | null = null;
      const nameRx = /(?:_skill_|function\s*[:=]\s*|✿FUNCTION✿\s*:\s*)([\w.\-]+)/i;
      const nameMatch = lookback.match(nameRx);
      if (nameMatch && nameMatch[1] && nameMatch[1].toLowerCase() !== 'not_found') {
        explicitName = nameMatch[1];
      }

      const name = explicitName ?? inferToolName(args, knownTools);
      if (name) {
        // Find span start — include the lookback marker if present
        let spanStart = at;
        if (nameMatch && nameMatch.index !== undefined) {
          spanStart = Math.max(0, at - 200) + nameMatch.index;
        }
        calls.push({
          id: newCallId(),
          type: 'function',
          function: { name, arguments: JSON.stringify(args) },
        });
        spans.push([spanStart, braceEnd + 1]);
      }
    } catch {
      /* skip */
    }
  }

  // Build cleaned output by removing consumed spans
  spans.sort((a, b) => a[0] - b[0]);
  let cleaned = '';
  let cursor = 0;
  for (const [s, e] of spans) {
    if (s > cursor) cleaned += content.slice(cursor, s);
    cursor = e;
  }
  if (cursor < content.length) cleaned += content.slice(cursor);

  // Strip stray qwen markers/noise tokens
  cleaned = cleaned
    .replace(/✿[A-Z_]+✿\s*:?/g, '')
    .replace(/<\/?tool_call>/gi, '')
    .replace(/^_skill_not_found\s*$/gim, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  if (calls.length > 0 && cleaned.length < 4) cleaned = '';

  return { calls, cleaned };
}

/** Find the index of the matching `}` for the `{` at `start`. -1 if unbalanced. */
function findMatchingBrace(s: string, start: number): number {
  if (s[start] !== '{') return -1;
  let depth = 0;
  let inStr = false;
  let escape = false;
  for (let i = start; i < s.length; i++) {
    const c = s[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (c === '\\') {
      escape = true;
      continue;
    }
    if (c === '"') {
      inStr = !inStr;
      continue;
    }
    if (inStr) continue;
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/**
 * Pick the best-matching tool name for a bare args object.
 *
 * Strategy (in priority order):
 *   1. Exact required-fields match (score from declared schema)
 *   2. Property-name overlap (any field appears in tool's properties)
 *   3. Single-non-meta-tool fallback: if there's exactly ONE skill-shaped
 *      tool exposed (the meta-tool `evolve_new_skill` excluded), assume
 *      that's what the model meant. Forged skills frequently have empty
 *      schemas because MockInference generates `{additionalProperties: true}`,
 *      so schema scoring is unreliable.
 *   4. Otherwise null — caller will leave the bare args in content as-is.
 */
function inferToolName(args: unknown, knownTools?: ToolDef[]): string | null {
  if (!knownTools || knownTools.length === 0) return null;
  const META_TOOLS = new Set(['evolve_new_skill']);
  const argKeys =
    args && typeof args === 'object' ? Object.keys(args as Record<string, unknown>) : [];

  // Score each tool by required + property overlap
  let best: { name: string; score: number; isMeta: boolean } | null = null;
  for (const t of knownTools) {
    const params = t.function.parameters as Record<string, unknown>;
    const required = (params?.required as string[] | undefined) ?? [];
    const props = Object.keys(
      (params?.properties as Record<string, unknown> | undefined) ?? {}
    );
    let score = 0;
    for (const r of required) if (argKeys.includes(r)) score += 3;
    for (const p of props) if (argKeys.includes(p)) score += 1;
    const isMeta = META_TOOLS.has(t.function.name);
    if (!best || score > best.score) {
      best = { name: t.function.name, score, isMeta };
    }
  }

  // Strong scoring match wins outright
  if (best && best.score >= 1) return best.name;

  // Fallback: if there's exactly one non-meta tool, assume the model
  // meant that one. Common case for forged skills with empty schemas.
  const skillTools = knownTools.filter((t) => !META_TOOLS.has(t.function.name));
  if (skillTools.length === 1 && skillTools[0]) return skillTools[0].function.name;

  return null;
}
